// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBackUp(arg1, arg2) {
  return window['go']['main']['App']['AddBackUp'](arg1, arg2);
}

export function DeleteActiveBackUp(arg1) {
  return window['go']['main']['App']['DeleteActiveBackUp'](arg1);
}

export function DeleteBackUp(arg1) {
  return window['go']['main']['App']['DeleteBackUp'](arg1);
}

export function GetActiveBackUps(arg1) {
  return window['go']['main']['App']['GetActiveBackUps'](arg1);
}

export function GetBackups() {
  return window['go']['main']['App']['GetBackups']();
}

export function RestoreActiveBackup(arg1) {
  return window['go']['main']['App']['RestoreActiveBackup'](arg1);
}

export function SelectSource() {
  return window['go']['main']['App']['SelectSource']();
}

export function TakeBackup(arg1, arg2) {
  return window['go']['main']['App']['TakeBackup'](arg1, arg2);
}
